server:
  port: 8080

spring:
  profiles:
    default: local

  application:
    name: ziine

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        format_sql: true
        query.fail_on_pagination_over_collection_fetch: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ziine.mailbot
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_S3_BUCKET}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      cdn:
        url: https://cdn.ziine.gallery/

jwt:
  secret-key: ${JWT_SECRET_KEY}

management:
  server:
    port: 1010
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health
    jmx:
      exposure:
        exclude: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  health:
    db:
      enabled: false
    mail:
      enabled: false
