spring:
  datasource:
    url: jdbc:mysql://localhost:33306/ziine?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: password

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        detector:
          enabled: true

  mail:
    mock: true

  cloud:
    aws:
      s3:
        mock: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret-key: clxksmsduftlaglekfflsekkkkkkkkkkkkkk
